sonar.organization=oussama604
sonar.projectKey=oussama604_cesizen_project
sonar.sources=app,resources/js
sonar.tests=tests
sonar.test.inclusions=tests/**/*.php
sonar.exclusions=bootstrap/cache/**,public/build/**,storage/**
sonar.coverage.exclusions=resources/js/**
sonar.php.coverage.reportPaths=coverage/clover.xml